stigapp/urls.py
from django.urls import path

from .views import (
    DiscordMessageListView,
    DiscordReactionListView,
    GardenMessageListView,
    TopMessageListView,
    # LeaderBoardView,
    home,
    about,
    page_not_found_404_view,
    export_csv,
    export_to_airtable,
    terms,
    privacy,
    # export_top_message_csv,
    # export_garden_message_csv,
    update_top_message_list,

)

urlpatterns = [
    # path('', home, name='home'),
    path('', home, name='home'),
    path('terms', terms, name='terms'),
    path('privacy', privacy, name='privacy'),
    path('garden-messages', GardenMessageListView.as_view(), name='garden_messages'),
    path('about', about, name='about'),
    path('top-messages', TopMessageListView.as_view(), name='top_messages'),
    # path('leaderboard', LeaderBoardView.as_view(), name='leaderboard-list'),
    # path('leaderboard/messages', DiscordMessageListView.as_view(), name='message-list'),
    # path('leaderboard/reactions', DiscordReactionListView.as_view(), name='reaction-list'),
    path('export_csv/<str:table>/<str:selected>/<str:test>', export_csv, name='export_csv'),
    path('export-airtable', export_to_airtable, name='export_to_airtable'),
    # path('export-tm', export_top_message_csv, name='export_topmessage'),
    # path('export-gm', export_garden_message_csv, name='export_gardenmessage'),
    path('update-tm', update_top_message_list, name='update_topmessage'),
]

stigsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from discordlogin import views


admin.site.site_header = 'Stigflow Admin'


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('stigapp.urls')),
    path('login', views.discord_login, name='login'),
    path('profile/<pk>', views.UserUpdateView.as_view(), name='profile'),
    path('communityprofile/<pk>', views.CommunityProfileUpdateView.as_view(), name='community-profile'),
    path('logout/', views.discord_logout, name='logout'),
    path("oauth2/", include('discordlogin.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

handler404 = 'stigapp.views.page_not_found_404_view'

discordlogin/models.py
import hashlib
import time
import datetime

from django.contrib.auth.models import (
    BaseUserManager,
    UserManager,
    AbstractBaseUser,
    AbstractUser,
)
from django.contrib.sites.models import Site
from django.db import models
from django.utils import timezone
from django.urls import reverse


################################################################
# Community profile settings
class CommunityProfile(models.Model):
    id = models.BigAutoField(primary_key=True)
    airtable_credentials = models.JSONField(
        blank=True,
        null=True,
        help_text="The Airtable key, base name, and table name associated with Stigsite"
    )
    monitored_channels = models.JSONField(
        blank=True,
        null=True,
        help_text="A list of channels within guilds the site will listen to"
    )
    monitored_guilds = models.JSONField(
        blank=True,
        null=True,
        help_text="A list of Discord guilds (servers) the site will listen to"
    )
    promotion_threshold = models.IntegerField()
    site_style = models.JSONField(
        blank=True,
        null=True,
        help_text="The Airtable key, base name, and table name associated with Stigsite"
    )
    django_site_id = models.ForeignKey(
        Site,
        db_column='django_site_id',
        related_name="+",
        on_delete=models.CASCADE,
        null=True
    )
    enable_twitter_handle_request = models.BooleanField(default=False)

    # extracted_urls_id = models.ForeignKey(
    #     "ExtractedUrls",
    #     db_column='extracted_urls_id',
    #     # related_name='extracted_urls',
    #     on_delete=models.CASCADE,
    #     help_text="The id of the EmbeddedMessage table entry with the message's extracted URLS"
    # )

    class Meta:
        managed = False
        db_table = 'community_profile'

    def get_absolute_url(self):
        return reverse('community-profile', kwargs={'pk': self.pk})


class UserManager(UserManager):

    def check_for_admin_authorization(self, discord_tag):
        """ Checks against a hardcoded list to see if a user is approved for admin privileges"""

        check = False
        approved_admin_users = [
            # 'insert discord_tags',
            'thompsgj#8407',
            'hobs#3386',
            'hobs#9238',
            'Sha#6179',
            'ronent#2267',
            'mariadyshel#6267',
            'richa#0775',
            'GideonRo#3175',
            'Irem#3362',
            'enti#1546',
            'bear100#9085',
            'acidlazzer#5796',
        ]
        if discord_tag in approved_admin_users:
            check = True

        return check

    def create_password(self):
        """  Makes a string for the mandatory, non-nullable password field.

        The password will not work even if a user knows it because authentication happens through Discord.
        """
        hash = hashlib.sha1()
        hash.update(str(time.time()).encode('utf-8'))
        return hash.hexdigest()[:7]

    def create_new_discord_user(self, user, password=None):
        """ Creates a user in the DiscordUser table.

        Uses the 'DiscordAuthenticationBackend' for authentication, not the standard Django auth backend.
        """

        discord_tag = '%s#%s' % (user['username'], user['discriminator'])
        permissions_boolean = self.check_for_admin_authorization(discord_tag)

        new_user = self.model(
            email='test@test.com'
        )
        new_user.id = user['id']
        new_user.username = discord_tag
        new_user.discord_tag = discord_tag
        new_user.twitter_handle = ''
        new_user.twitter_username = ''
        new_user.avatar = user['avatar']
        new_user.public_flags = user['public_flags']
        new_user.flags = user['flags']
        new_user.locale = user['locale']
        new_user.mfa_enabled = user['mfa_enabled']
        new_user.active = True
        new_user.staff = permissions_boolean
        new_user.admin = permissions_boolean

        password = self.create_password()
        new_user.set_password(password)
        new_user.save(using=self._db)
        return new_user


class User(AbstractUser):
    """ A user who has logged in to stigsite through Discord """

    _DATABASE = 'supabase'

    objects = UserManager()

    # Discord-specific user attributes
    id = models.BigIntegerField(primary_key=True)
    username = models.CharField(max_length=100, unique=True)
    discord_tag = models.CharField(max_length=100, unique=True)
    twitter_handle = models.CharField(max_length=100, blank=True, null=True)
    twitter_username = models.CharField(max_length=100, blank=True, null=True)
    first_name = models.CharField(max_length=100, null=True)
    last_name = models.CharField(max_length=100, null=True)
    avatar = models.CharField(blank=True, null=True, max_length=100)
    public_flags = models.IntegerField()
    flags = models.IntegerField()
    locale = models.CharField(max_length=100)
    mfa_enabled = models.BooleanField()
    date_joined = models.DateTimeField(default=timezone.now)
    last_login = models.DateTimeField(default=timezone.now)

    django_site_id = models.ForeignKey(
        Site,
        verbose_name="Team URL",
        db_column='django_site_id',
        related_name="+",
        on_delete=models.CASCADE,
        null=True
    )

    # Django admin user attributes
    # authenticated = models.BooleanField(default=True)
    active = models.BooleanField(default=True)
    staff = models.BooleanField(default=True)
    admin = models.BooleanField(default=True)
    email = models.CharField(max_length=255, default="test@test.com")
    requested_twitter_handle = models.BooleanField(default=False)

    USERNAME_FIELD = 'discord_tag'
    REQUIRED_FIELDS = []

    class Meta:
        managed = False
        db_table = 'auth_user'
        # app_label = 'user_data'

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.discord_tag

    def get_short_name(self):
        return self.discord_tag

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_active(self):
        return self.active

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_admin(self):
        return self.admin

    @property
    def is_superuser(self):
        return self.admin

    @property
    def is_authenticated(self):
        return True

    def get_absolute_url(self):
        return reverse('profile', kwargs={'pk': self.pk})


# class DiscordUserManager(BaseUserManager):

#     def check_for_admin_authorization(self, discord_tag):
#         """ Checks against a hardcoded list to see if a user is approved for admin privileges"""

#         check = False
#         approved_admin_users = [
#             # 'insert discord_tags',
#             'thompsgj#8407'
#         ]
#         if discord_tag in approved_admin_users:
#             check = True

#         return check

#     def create_password(self):
#         """  Makes a string for the mandatory, non-nullable password field.

#         The password will not work even if a user knows it because authentication happens through Discord.
#         """
#         hash = hashlib.sha1()
#         hash.update(str(time.time()).encode('utf-8'))
#         return hash.hexdigest()[:7]

#     def create_new_discord_user(self, user, password=None):
#         """ Creates a user in the DiscordUser table.

#         Uses the 'DiscordAuthenticationBackend' for authentication, not the standard Django auth backend.
#         """

#         discord_tag = '%s#%s' % (user['username'], user['discriminator'])
#         permissions_boolean = self.check_for_admin_authorization(discord_tag)

#         new_user = self.model(
#             email='test@test.com'
#         )
#         new_user.id = user['id']
#         new_user.discord_tag = discord_tag
#         new_user.avatar = user['avatar']
#         new_user.public_flags = user['public_flags']
#         new_user.flags = user['flags']
#         new_user.locale = user['locale']
#         new_user.mfa_enabled = user['mfa_enabled']
#         new_user.active = True
#         new_user.staff = permissions_boolean
#         new_user.admin = permissions_boolean

#         password = self.create_password()
#         new_user.set_password(password)
#         new_user.save(using=self._db)
#         return new_user


# class DiscordUser(AbstractBaseUser):
#     """ A user who has logged in to stigsite through Discord """

#     _DATABASE = 'supabase'

#     objects = DiscordUserManager()

#     # Discord-specific user attributes
#     id = models.BigIntegerField(primary_key=True)
#     discord_tag = models.CharField(max_length=100, unique=True)
#     avatar = models.CharField(blank=True, null=True, max_length=100)
#     public_flags = models.IntegerField()
#     flags = models.IntegerField()
#     locale = models.CharField(max_length=100)
#     mfa_enabled = models.BooleanField()
#     last_login = models.DateTimeField(null=True)

#     # Django admin user attributes
#     # authenticated = models.BooleanField(default=True)
#     active = models.BooleanField(default=True)
#     staff = models.BooleanField(default=True)
#     admin = models.BooleanField(default=True)
#     email = models.CharField(max_length=255, default="test@test.com")

#     USERNAME_FIELD = 'discord_tag'
#     REQUIRED_FIELDS = []

#     class Meta:
#         managed = False
#         db_table = 'discord_user'

#     def __str__(self):
#         return self.email

#     def get_full_name(self):

stigapp/templates/stigapp/about.html
{% extends "stigapp/base.html" %}
{% load static %}

{% block content %}

<p>
    <img src="{% static 'stigapp/images/tecround.png' %}" alt="Token Engineering Commons logo with the letters TEC projecting forward and upward" width=50px height=50px>
    <a href ="https://tecommons.org/" target="_blank">Token Engineering Commons</a>
</p>

<p>
    <img src="https://uploads-ssl.webflow.com/62ca2f7237b2815119b970f9/62cefc9f5bc05e110328f101_Group%203020(1).svg" alt="DAOStack logo with 4 transparent black diamonds on top of each other" width=32px height=50px>
    <a href="https://www.csensemakers.com/" target="_blank">Common Sense[makers]</a>
</p>

<p>
    <img src="https://daostack.io/static/media/daostack_icon_2e2e2e_thin.90807b23.svg" alt="DAOStack logo with 4 transparent black diamonds on top of each other" width=32px height=50px>
    <a href="https://daostack.io" target="_blank">DAOstack</a>
</p>

<p>Point of Contact: greg@tangibleai.com</p>
{% endblock content %}

stigapp/templates/stigapp/discordmessage_list.html
<p>Discord Message List</p>

{% for message in discordmessage_list %}
    <p>{{ message.author.display_name }}: {{ message.content }}</p>
{% endfor %}

stigapp/templates/stigapp/discordreaction_list.html
<p>Discord Reaction List</p>

{% for reaction in discordreaction_list %}
    <p>{{ reaction.message_id }}: {% for emoji in reaction.previous_reactions %}{{emoji.emoji}}{% endfor %}</p>
{% endfor %}

stigapp/templates/stigapp/gardenmessage_list.html
{% extends "stigapp/base.html" %}
{% load static %}

{% block content %}
    {% if user.is_authenticated %}
        {% if user.is_staff or user.is_admin %}
            <div class="row">
                <div class="col-6">
                    <h2>Garden Message List</h2>
                </div>

                <div class="col-6">
                    <a href='{% url "export_csv" table="garden" selected="all" test="true" %}'>
                        <button type="button" class="btn btn-secondary btn-sm">
                            Test Export
                        </button>
                    </a>
                    <a href='{% url "export_csv" table="garden" selected="unexported" test="false"%}'>
                        <button type="button" class="btn btn-primary btn-sm">
                            Export New
                        </button>
                    </a>
                    <a href='{% url "export_to_airtable" %}'>
                        <button type="button" class="btn btn-primary btn-sm">
                            Export to Airtable
                        </button>
                    </a>
                </div>
            </div>

            <div class="tableFixHead">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Author</th>
                            <th scope="col">Twitter Handle</th>
                            <th scope="col">Guild</th>
                            <th scope="col">Channel</th>
                            <th scope="col">Message ID</th>
                            <th scope="col">Message Type</th>
                            <th scope="col">Original Message</th>
                            <th scope="col">Authorship</th>
                            <th scope="col">Editable Message</th>
                            <th scope="col">Edited At</th>
                            <th scope="col">All Reactions</th>
                            <th scope="col">Unique Reactions</th>
                            <th scope="col">All Emojis</th>
                            <th scope="col">Unique Emojis</th>
                            <th scope="col">Totals by Emoji</th>
                            <th scope="col">Total Users</th>
                            <th scope="col">Unique Users</th>
                            <th scope="col">Total User List</th>
                            <th scope="col">Unique User List</th>
                            <th scope="col">Extracted URL</th>
                            <th scope="col">Exported At</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for message in gardenmessage_list %}
                            <tr>
                                <td>{{ message.author_discord_username }}</td>
                                <td>{{ message.twitter_handle }}</td>
                                <td>{{ message.guild_name }}</td>
                                <td>{{ message.channel_name }}</td>
                                <td>
                                    {% if message.jump_url == None %}
                                        {{ message.message_id }}
                                    {% else %}
                                        <a href="{{message.jump_url}}" target="_blank">
                                            {{ message.message_id }}
                                        </a>
                                    {% endif %}
                                </td>
                                <td>{{ message.message_type }}</td>
                                <td>{{ message.original_message }}</td>
                                <td>{{ message.authorship_datetime }}</td>
                                <td>{{ message.editable_message }}</td>
                                <td>{{ message.edited_at }}</td>
                                <td>{{ message.reaction_count }}</td>
                                <td>{{ message.unique_reaction_count }}</td>
                                <td>
                                    {% for emoji in message.emoji_list %}
                                        {{emoji}}
                                    {% endfor %}
                                </td>
                                <td>
                                    {% for emoji in message.unique_emoji_list %}
                                        {{emoji}}
                                    {% endfor %}
                                </td>
                                <td>
                                    {% for emoji in message.counts_by_emoji %}
                                        <p>{{emoji}}: {{message.counts_by_emoji|dict_key:emoji}}</p>
                                    {% endfor %}
                                </td>
                                <td>{{ message.user_count }}</td>
                                <td>{{ message.unique_user_count }}</td>
                                <td>
                                    {% for user in message.user_list %}
                                        {{ user.name }}{{ user.discriminator }},
                                    {% endfor %}
                                </td>
                                <td>
                                    {% for user in message.unique_user_list %}
                                        {{ user.name }}{{ user.discriminator }},
                                    {% endfor %}
                                </td>
                                <td>
                                    {% if message.extracted_urls_id.id == '' %}
                                        None
                                    {% else %}
                                        {{ message.extracted_urls_id.url_list.0 }}
                                    {% endif %}
                                </td>
                                <td>{{ message.exported_at }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

        {% endif %}
    {% endif %}
{% endblock content %}

stigapp/templates/stigapp/home.html
{% extends "stigapp/base.html" %}
{% load static %}

{% block content %}

<div id="intro-container">
    <div id="welcome-copy-container">
        <h1 class="mb-7">Communities thrive in understanding</h1>

        <p>Your community and it's important ideas should not be limited by platforms optimized for keeping your attention focused on them. Make sense of what's important to your community across communities!</p>
    </div>

    <div id="join-ctas-container">
        {% if user.is_authenticated %}
        {% else %}
        <a class="btn btn-primary btn-lg" href="{% url 'login' %}">Join us!</a>
        {% endif %}
    </div>
</div>
{% endblock content %}

stigapp/templates/stigapp/privacy.html
{% extends "stigapp/base.html" %}
{% load static %}

{% block content %}

<p>privacy</p>
{% endblock content %}

stigapp/templates/stigapp/terms.html
{% extends "stigapp/base.html" %}
{% load static %}

{% block content %}

<p>terms</p>
{% endblock content %}

stigapp/templates/stigapp/topmessage_list.html
{% extends "stigapp/base.html" %}
{% load static %}

{% block content %}
    {% if user.is_authenticated %}
        {% if user.is_staff or user.is_admin %}
            <div class="row">
                <div class="col-6">
                    <h2>Top Message List</h2>
                </div>

                <!-- <div class="col-2">
                    <a href='{% url "update_topmessage" %}'>
                        <button type="button" class="btn btn-primary btn-sm">
                            Update List
                        </button>
                    </a>
                </div> -->

                <div class="col-6">
                    <a href='{% url "export_csv" table="top" selected="all" test="true" %}'>
                        <button type="button" class="btn btn-secondary btn-sm">
                            Test Export
                        </button>
                    </a>

                    <a href='{% url "export_csv" table="top" selected="unexported" test="false" %}'>
                        <button type="button" class="btn btn-primary btn-sm">
                            Export New
                        </button>
                    </a>
                </div>
            </div>

            <div class="tableFixHead">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Author</th>
                            <th scope="col">Twitter Handle</th>
                            <th scope="col">Guild</th>
                            <th scope="col">Channel</th>
                            <th scope="col">Message ID</th>
                            <th scope="col">Message Type</th>
                            <th scope="col">Message</th>
                            <th scope="col">Authorship</th>
                            <th scope="col">Editable Message</th>
                            <th scope="col">Edited At</th>
                            <th scope="col">All Reactions</th>
                            <th scope="col">Unique Reactions</th>
                            <th scope="col">All Emojis</th>
                            <th scope="col">Unique Emojis</th>
                            <th scope="col">Totals by Emoji</th>
                            <th scope="col">Total Users</th>
                            <th scope="col">Unique Users</th>
                            <th scope="col">Total User List</th>
                            <th scope="col">Unique User List</th>
                            <th scope="col">Extracted URL</th>
                            <th scope="col">Added to Garden</th>
                            <th scope="col">Exported At</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for message in topmessage_list %}
                            <tr>
                                <td>{{ message.author_discord_username }}</td>
                                <td>{{ message.twitter_handle }}</td>
                                <td>{{ message.guild_name }}</td>
                                <td>{{ message.channel_name }}</td>
                                <td>
                                    {% if message.jump_url == None %}
                                        {{ message.message_id }}
                                    {% else %}
                                        <a href="{{message.jump_url}}" target="_blank">
                                            {{ message.message_id }}
                                        </a>
                                    {% endif %}
                                </td>
                                <td>{{ message.message_type }}</td>
                                <td>{{ message.original_message }}</td>
                                <td>{{ message.authorship_datetime }}</td>
                                <td>{{ message.editable_message }}</td>
                                <td>{{ message.edited_at }}</td>
                                <td>{{ message.reaction_count }}</td>
                                <td>{{ message.unique_reaction_count }}</td>
                                <td>
                                    {% for emoji in message.emoji_list %}
                                        {{emoji}}
                                    {% endfor %}
                                </td>
                                <td>
                                    {% for emoji in message.unique_emoji_list %}
                                        {{emoji}}
                                    {% endfor %}
                                </td>
                                <td>
                                    {% for emoji in message.counts_by_emoji %}
                                        <p>{{emoji}}: {{message.counts_by_emoji|dict_key:emoji}}</p>
                                    {% endfor %}
                                </td>
                                <td>{{ message.user_count }}</td>
                                <td>{{ message.unique_user_count }}</td>
                                <td>
                                    {% for user in message.user_list %}
                                        {{ user.name }}{{ user.discriminator }},
                                    {% endfor %}
                                </td>
                                <td>
                                    {% for user in message.unique_user_list %}
                                        {{ user.name }}{{ user.discriminator }},
                                    {% endfor %}
                                </td>
                                <td>
                                    {% if message.extracted_urls_id.id == '' %}
                                        None
                                    {% else %}
                                        {{ message.extracted_urls_id.url_list.0 }}
                                    {% endif %}
                                </td>
                                <td>{{ message.added_to_garden }}</td>
                                <td>{{ message.exported_at }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

        {% endif %}
    {% endif %}
{% endblock content %}